import { describe, expect, it } from 'vitest';
import { teams } from '../data/teams';
import { createDoubleRoundRobin } from '../domain/fixtures';
import { normalizeMarketProbabilities } from '../calibration/market';
import { createRng } from '../simulation/rng';
import { IndependentPoissonModel } from '../simulation/score-model';
import { simulateSeason } from '../simulation/season-simulator';
import { applyResult, emptyTable, sortLeagueTable } from '../domain/standings';
import { applyDynamicMatch, closeDynamicSeason, createDynamicStrength, dynamicParameters, effectiveRatings } from '../simulation/dynamic-strength';
import { toStrengthIndices, toStrengthLayers } from '../simulation/strength-index';
import { assessUpset, scoreUpset } from '../simulation/match-probability';

describe('league engine',()=>{
  it('creates exactly 380 home-and-away fixtures and 38 matches per club',()=>{ const fixtures=createDoubleRoundRobin(teams.map(t=>t.id)); expect(fixtures).toHaveLength(380); for(const team of teams) expect(fixtures.filter(f=>f.homeId===team.id||f.awayId===team.id)).toHaveLength(38); });
  it('normalizes a market and rejects invalid values',()=>{ const result=normalizeMarketProbabilities({arsenal:2,'man-city':1},teams); expect(Object.values(result).reduce((a,b)=>a+b,0)).toBeCloseTo(1); expect(()=>normalizeMarketProbabilities({arsenal:-1},teams)).toThrow(); expect(()=>normalizeMarketProbabilities({},teams)).toThrow(); });
  it('is deterministic for a seed and produces non-negative integer scores',()=>{ const model=new IndependentPoissonModel(); const ratings=Object.fromEntries(teams.map(t=>[t.id,0])); const a=model.simulateScore(teams[0],teams[1],ratings,createRng(4)); const b=model.simulateScore(teams[0],teams[1],ratings,createRng(4)); expect(a).toEqual(b); expect(Number.isInteger(a.homeGoals)&&a.homeGoals>=0).toBe(true); });
  it('accumulates points and orders by points, goal difference, then goals scored',()=>{ const table=emptyTable(['a','b']); applyResult(table,{homeId:'a',awayId:'b',round:1},{homeGoals:2,awayGoals:1,lambdaHome:0,lambdaAway:0}); const sorted=sortLeagueTable(table); expect(sorted[0].teamId).toBe('a'); expect(sorted[0].points).toBe(3); expect(sorted[0].goalDifference).toBe(1); });
  it('plays a complete reproducible season',()=>{ const fixtures=createDoubleRoundRobin(teams.map(t=>t.id)); const ratings=Object.fromEntries(teams.map(t=>[t.id,0])); const run=(seed:number)=>simulateSeason(teams,fixtures,ratings,createRng(seed),new IndependentPoissonModel()); const season=run(5); expect(season.matches).toHaveLength(380); expect(season.table.every(row=>row.played===38)).toBe(true); expect(run(5).championId).toBe(season.championId); });
  it('gives an unexpected upset more short-term lift than an expected win, without exceeding the cap',()=>{ const pair=[{id:'sunderland',name:'Sunderland',color:'#f00'},{id:'arsenal',name:'Arsenal',color:'#fff'}]; const ratings={sunderland:-1,arsenal:1}; const upset=createDynamicStrength(pair,ratings); const expected=createDynamicStrength(pair,ratings); const fixture={homeId:'sunderland',awayId:'arsenal',round:1}; applyDynamicMatch(upset,fixture,{homeGoals:2,awayGoals:0,lambdaHome:.35,lambdaAway:2.4}); applyDynamicMatch(expected,fixture,{homeGoals:2,awayGoals:0,lambdaHome:2.4,lambdaAway:.35}); expect(upset.sunderland.form).toBeGreaterThan(expected.sunderland.form); for(let i=0;i<30;i++)applyDynamicMatch(upset,fixture,{homeGoals:2,awayGoals:0,lambdaHome:.35,lambdaAway:2.4}); expect(Math.abs(upset.sunderland.form)).toBeLessThanOrEqual(dynamicParameters.fMax); });
  it('uses tier only as season-to-season protection, not an initial match bonus',()=>{ const clubs=[{id:'arsenal',name:'Arsenal',color:'#f00'},{id:'sunderland',name:'Sunderland',color:'#fff'}]; const state=createDynamicStrength(clubs,{arsenal:0,sunderland:0}); expect(state.arsenal.form).toBe(state.sunderland.form); state.arsenal.seasonShock=-12; state.sunderland.seasonShock=-12; state.arsenal.history=-.5; state.sunderland.history=-.5; closeDynamicSeason(state,{arsenal:38,sunderland:38}); expect(state.arsenal.base).toBeGreaterThan(state.sunderland.base); });
  it('uses a translation-invariant neutral expected-result strength index',()=>{ const clubs=teams.slice(0,4); const ratings=Object.fromEntries(clubs.map((team,index)=>[team.id,index*.1])); const shifted=Object.fromEntries(clubs.map(team=>[team.id,ratings[team.id]+7])); const first=toStrengthIndices(clubs,ratings); const second=toStrengthIndices(clubs,shifted); expect(second).toEqual(first); expect(Object.values(first).reduce((sum,value)=>sum+value,0)/clubs.length).toBe(50); });
  it('stores base, medium and form layers while weighting form once',()=>{ const clubs=teams.slice(0,3); const state=createDynamicStrength(clubs,Object.fromEntries(clubs.map(team=>[team.id,0]))); state[clubs[0].id].medium=.08; state[clubs[0].id].form=.2; const layers=toStrengthLayers(clubs,state); expect(layers[clubs[0].id].noForm).toBeGreaterThan(layers[clubs[0].id].base); expect(layers[clubs[0].id].current).toBeGreaterThan(layers[clubs[0].id].noForm); expect(effectiveRatings(state)[clubs[0].id]).toBeCloseTo(.08+dynamicParameters.formWeight*.2); });
  it('centres the long-run base coordinate after every season',()=>{ const clubs=teams.slice(0,4); const state=createDynamicStrength(clubs,Object.fromEntries(clubs.map((team,index)=>[team.id,index*.1]))); for(const team of clubs)state[team.id].seasonShock=.4; closeDynamicSeason(state,Object.fromEntries(clubs.map(team=>[team.id,38]))); const mean=Object.values(state).reduce((sum,value)=>sum+value.base,0)/clubs.length; expect(mean).toBeCloseTo(0,10); });
  it('only applies score margin after a genuine underdog has won',()=>{ expect(scoreUpset(.368,.40,8)).toBeNull(); expect(assessUpset(1.4,1.25,'away',8)).toBeNull(); const narrow=assessUpset(.35,2.4,'home',1); const emphatic=assessUpset(.35,2.4,'home',4); expect(narrow).not.toBeNull(); expect(emphatic!.upsetIndex).toBeGreaterThan(narrow!.upsetIndex); });
});
